### ISSUE TITLE
Setup/Search, crash when no machines listed

### ISSUE THREAD

**Issue by totalAldo** [spyderbat/spydertop#1]
In Setup:Search, when a string is entered where no machines are listed, and < Continue > Is selected, an error is thrown:
  
Traceback (most recent call last):
  File "/Users/anon/Library/Python/3.10/bin/./spydertop", line 33, in <module>
    sys.exit(load_entry_point('spydertop==0.4.1', 'console_scripts', 'spydertop')())
  File "/Users/anon/Library/Python/3.10/lib/python/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/anon/Library/Python/3.10/lib/python/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/anon/Library/Python/3.10/lib/python/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/anon/Library/Python/3.10/lib/python/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/anon/Library/Python/3.10/lib/python/site-packages/spydertop/cli.py", line 216, in cli
    start_screen(config)
  File "/Users/anon/Library/Python/3.10/lib/python/site-packages/spydertop/screens/__init__.py", line 45, in start_screen
    screen.play(
  File "/Users/anon/Library/Python/3.10/lib/python/site-packages/asciimatics/screen.py", line 1606, in play
    self.draw_next_frame(repeat=repeat)
  File "/Users/anon/Library/Python/3.10/lib/python/site-packages/asciimatics/screen.py", line 1694, in draw_next_frame
    event = scene.process_event(event)
  File "/Users/anon/Library/Python/3.10/lib/python/site-packages/asciimatics/scene.py", line 105, in process_event
    event = effect.process_event(event)
  File "/Users/anon/Library/Python/3.10/lib/python/site-packages/spydertop/screens/config.py", line 120, in process_event
    self._on_submit()
  File "/Users/anon/Library/Python/3.10/lib/python/site-packages/spydertop/screens/config.py", line 491, in <lambda>
    self._on_submit = lambda: answers[list_box.value][1]()
TypeError: list indices must be integers or slices, not NoneType

**Comment by totalAldo** [comment]
Selecting the global machine ID also throws this error.
