### ISSUE TITLE
Excessive DEBUG messages when playing example

### ISSUE THREAD

**Issue by bsmith1180** [spyderbat/spydertop#4]
Running `docker run -it spyderbat/spydertop -i examples/minikube-sock-shop.json.gz`, I get a spew of messages on the console when I exit:

````
[DEBUG]: Traceback (most recent call last):
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 692, in urlopen
[DEBUG]:     conn = self._get_conn(timeout=pool_timeout)
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 281, in _get_conn
[DEBUG]:     return conn or self._new_conn()
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 235, in _new_conn
[DEBUG]:     conn = self.ConnectionCls(
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 130, in __init__
[DEBUG]:     _HTTPConnection.__init__(self, *args, **kw)
[DEBUG]:   File "/usr/local/lib/python3.10/http/client.py", line 853, in __init__
[DEBUG]:     self._validate_host(self.host)
[DEBUG]:   File "/usr/local/lib/python3.10/http/client.py", line 1235, in _validate_host
[DEBUG]:     raise InvalidURL(f"URL can't contain control characters. {host!r} "
[DEBUG]: http.client.InvalidURL: URL can't contain control characters. "<_io.textiowrapper name='examples" (found at least ' ')
[DEBUG]:
[DEBUG]: During handling of the above exception, another exception occurred:
[DEBUG]:
[DEBUG]: Traceback (most recent call last):
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/spydertop/model.py", line 476, in log_api
[DEBUG]:     response = self._http_client.request(
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/request.py", line 78, in request
[DEBUG]:     return self.request_encode_body(
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/request.py", line 170, in request_encode_body
[DEBUG]:     return self.urlopen(method, url, **extra_kw)
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/poolmanager.py", line 376, in urlopen
[DEBUG]:     response = conn.urlopen(method, u.request_uri, **kw)
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
[DEBUG]:     retries = retries.increment(
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
[DEBUG]:     raise six.reraise(type(error), error, _stacktrace)
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise
[DEBUG]:     raise value.with_traceback(tb)
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 692, in urlopen
[DEBUG]:     conn = self._get_conn(timeout=pool_timeout)
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 281, in _get_conn
[DEBUG]:     return conn or self._new_conn()
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 235, in _new_conn
[DEBUG]:     conn = self.ConnectionCls(
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 130, in __init__
[DEBUG]:     _HTTPConnection.__init__(self, *args, **kw)
[DEBUG]:   File "/usr/local/lib/python3.10/http/client.py", line 853, in __init__
[DEBUG]:     self._validate_host(self.host)
[DEBUG]:   File "/usr/local/lib/python3.10/http/client.py", line 1235, in _validate_host
[DEBUG]:     raise InvalidURL(f"URL can't contain control characters. {host!r} "
[DEBUG]: urllib3.exceptions.ProtocolError: ('Connection aborted.', InvalidURL('URL can\'t contain control characters. "<_io.textiowrapper name=\'examples" (found at least \' \')'))
[DEBUG]:
[DEBUG]: Traceback (most recent call last):
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 692, in urlopen
[DEBUG]:     conn = self._get_conn(timeout=pool_timeout)
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 281, in _get_conn
[DEBUG]:     return conn or self._new_conn()
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 235, in _new_conn
[DEBUG]:     conn = self.ConnectionCls(
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 130, in __init__
[DEBUG]:     _HTTPConnection.__init__(self, *args, **kw)
[DEBUG]:   File "/usr/local/lib/python3.10/http/client.py", line 853, in __init__
[DEBUG]:     self._validate_host(self.host)
[DEBUG]:   File "/usr/local/lib/python3.10/http/client.py", line 1235, in _validate_host
[DEBUG]:     raise InvalidURL(f"URL can't contain control characters. {host!r} "
[DEBUG]: http.client.InvalidURL: URL can't contain control characters. "<_io.textiowrapper name='examples" (found at least ' ')
[DEBUG]:
[DEBUG]: During handling of the above exception, another exception occurred:
[DEBUG]:
[DEBUG]: Traceback (most recent call last):
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/spydertop/model.py", line 476, in log_api
[DEBUG]:     response = self._http_client.request(
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/request.py", line 78, in request
[DEBUG]:     return self.request_encode_body(
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/request.py", line 170, in request_encode_body
[DEBUG]:     return self.urlopen(method, url, **extra_kw)
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/poolmanager.py", line 376, in urlopen
[DEBUG]:     response = conn.urlopen(method, u.request_uri, **kw)
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
[DEBUG]:     retries = retries.increment(
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
[DEBUG]:     raise six.reraise(type(error), error, _stacktrace)
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise
[DEBUG]:     raise value.with_traceback(tb)
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 692, in urlopen
[DEBUG]:     conn = self._get_conn(timeout=pool_timeout)
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 281, in _get_conn
[DEBUG]:     return conn or self._new_conn()
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 235, in _new_conn
[DEBUG]:     conn = self.ConnectionCls(
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 130, in __init__
[DEBUG]:     _HTTPConnection.__init__(self, *args, **kw)
[DEBUG]:   File "/usr/local/lib/python3.10/http/client.py", line 853, in __init__
[DEBUG]:     self._validate_host(self.host)
[DEBUG]:   File "/usr/local/lib/python3.10/http/client.py", line 1235, in _validate_host
[DEBUG]:     raise InvalidURL(f"URL can't contain control characters. {host!r} "
[DEBUG]: urllib3.exceptions.ProtocolError: ('Connection aborted.', InvalidURL('URL can\'t contain control characters. "<_io.textiowrapper name=\'examples" (found at least \' \')'))
[DEBUG]:
[DEBUG]: Traceback (most recent call last):
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 692, in urlopen
[DEBUG]:     conn = self._get_conn(timeout=pool_timeout)
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 281, in _get_conn
[DEBUG]:     return conn or self._new_conn()
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 235, in _new_conn
[DEBUG]:     conn = self.ConnectionCls(
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 130, in __init__
[DEBUG]:     _HTTPConnection.__init__(self, *args, **kw)
[DEBUG]:   File "/usr/local/lib/python3.10/http/client.py", line 853, in __init__
[DEBUG]:     self._validate_host(self.host)
[DEBUG]:   File "/usr/local/lib/python3.10/http/client.py", line 1235, in _validate_host
[DEBUG]:     raise InvalidURL(f"URL can't contain control characters. {host!r} "
[DEBUG]: http.client.InvalidURL: URL can't contain control characters. "<_io.textiowrapper name='examples" (found at least ' ')
[DEBUG]:
[DEBUG]: During handling of the above exception, another exception occurred:
[DEBUG]:
[DEBUG]: Traceback (most recent call last):
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/spydertop/model.py", line 476, in log_api
[DEBUG]:     response = self._http_client.request(
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/request.py", line 78, in request
[DEBUG]:     return self.request_encode_body(
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/request.py", line 170, in request_encode_body
[DEBUG]:     return self.urlopen(method, url, **extra_kw)
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/poolmanager.py", line 376, in urlopen
[DEBUG]:     response = conn.urlopen(method, u.request_uri, **kw)
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
[DEBUG]:     retries = retries.increment(
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
[DEBUG]:     raise six.reraise(type(error), error, _stacktrace)
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise
[DEBUG]:     raise value.with_traceback(tb)
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 692, in urlopen
[DEBUG]:     conn = self._get_conn(timeout=pool_timeout)
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 281, in _get_conn
[DEBUG]:     return conn or self._new_conn()
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 235, in _new_conn
[DEBUG]:     conn = self.ConnectionCls(
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 130, in __init__
[DEBUG]:     _HTTPConnection.__init__(self, *args, **kw)
[DEBUG]:   File "/usr/local/lib/python3.10/http/client.py", line 853, in __init__
[DEBUG]:     self._validate_host(self.host)
[DEBUG]:   File "/usr/local/lib/python3.10/http/client.py", line 1235, in _validate_host
[DEBUG]:     raise InvalidURL(f"URL can't contain control characters. {host!r} "
[DEBUG]: urllib3.exceptions.ProtocolError: ('Connection aborted.', InvalidURL('URL can\'t contain control characters. "<_io.textiowrapper name=\'examples" (found at least \' \')'))
[DEBUG]:
[DEBUG]: Traceback (most recent call last):
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 692, in urlopen
[DEBUG]:     conn = self._get_conn(timeout=pool_timeout)
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 281, in _get_conn
[DEBUG]:     return conn or self._new_conn()
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 235, in _new_conn
[DEBUG]:     conn = self.ConnectionCls(
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 130, in __init__
[DEBUG]:     _HTTPConnection.__init__(self, *args, **kw)
[DEBUG]:   File "/usr/local/lib/python3.10/http/client.py", line 853, in __init__
[DEBUG]:     self._validate_host(self.host)
[DEBUG]:   File "/usr/local/lib/python3.10/http/client.py", line 1235, in _validate_host
[DEBUG]:     raise InvalidURL(f"URL can't contain control characters. {host!r} "
[DEBUG]: http.client.InvalidURL: URL can't contain control characters. "<_io.textiowrapper name='examples" (found at least ' ')
[DEBUG]:
[DEBUG]: During handling of the above exception, another exception occurred:
[DEBUG]:
[DEBUG]: Traceback (most recent call last):
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/spydertop/model.py", line 476, in log_api
[DEBUG]:     response = self._http_client.request(
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/request.py", line 78, in request
[DEBUG]:     return self.request_encode_body(
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/request.py", line 170, in request_encode_body
[DEBUG]:     return self.urlopen(method, url, **extra_kw)
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/poolmanager.py", line 376, in urlopen
[DEBUG]:     response = conn.urlopen(method, u.request_uri, **kw)
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
[DEBUG]:     retries = retries.increment(
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
[DEBUG]:     raise six.reraise(type(error), error, _stacktrace)
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise
[DEBUG]:     raise value.with_traceback(tb)
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 692, in urlopen
[DEBUG]:     conn = self._get_conn(timeout=pool_timeout)
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 281, in _get_conn
[DEBUG]:     return conn or self._new_conn()
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 235, in _new_conn
[DEBUG]:     conn = self.ConnectionCls(
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 130, in __init__
[DEBUG]:     _HTTPConnection.__init__(self, *args, **kw)
[DEBUG]:   File "/usr/local/lib/python3.10/http/client.py", line 853, in __init__
[DEBUG]:     self._validate_host(self.host)
[DEBUG]:   File "/usr/local/lib/python3.10/http/client.py", line 1235, in _validate_host
[DEBUG]:     raise InvalidURL(f"URL can't contain control characters. {host!r} "
[DEBUG]: urllib3.exceptions.ProtocolError: ('Connection aborted.', InvalidURL('URL can\'t contain control characters. "<_io.textiowrapper name=\'examples" (found at least \' \')'))
[DEBUG]:
[DEBUG]: Traceback (most recent call last):
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 692, in urlopen
[DEBUG]:     conn = self._get_conn(timeout=pool_timeout)
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 281, in _get_conn
[DEBUG]:     return conn or self._new_conn()
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 235, in _new_conn
[DEBUG]:     conn = self.ConnectionCls(
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 130, in __init__
[DEBUG]:     _HTTPConnection.__init__(self, *args, **kw)
[DEBUG]:   File "/usr/local/lib/python3.10/http/client.py", line 853, in __init__
[DEBUG]:     self._validate_host(self.host)
[DEBUG]:   File "/usr/local/lib/python3.10/http/client.py", line 1235, in _validate_host
[DEBUG]:     raise InvalidURL(f"URL can't contain control characters. {host!r} "
[DEBUG]: http.client.InvalidURL: URL can't contain control characters. "<_io.textiowrapper name='examples" (found at least ' ')
[DEBUG]:
[DEBUG]: During handling of the above exception, another exception occurred:
[DEBUG]:
[DEBUG]: Traceback (most recent call last):
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/spydertop/model.py", line 476, in log_api
[DEBUG]:     response = self._http_client.request(
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/request.py", line 78, in request
[DEBUG]:     return self.request_encode_body(
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/request.py", line 170, in request_encode_body
[DEBUG]:     return self.urlopen(method, url, **extra_kw)
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/poolmanager.py", line 376, in urlopen
[DEBUG]:     response = conn.urlopen(method, u.request_uri, **kw)
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
[DEBUG]:     retries = retries.increment(
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
[DEBUG]:     raise six.reraise(type(error), error, _stacktrace)
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise
[DEBUG]:     raise value.with_traceback(tb)
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 692, in urlopen
[DEBUG]:     conn = self._get_conn(timeout=pool_timeout)
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 281, in _get_conn
[DEBUG]:     return conn or self._new_conn()
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 235, in _new_conn
[DEBUG]:     conn = self.ConnectionCls(
[DEBUG]:   File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 130, in __init__
[DEBUG]:     _HTTPConnection.__init__(self, *args, **kw)
[DEBUG]:   File "/usr/local/lib/python3.10/http/client.py", line 853, in __init__
[DEBUG]:     self._validate_host(self.host)
[DEBUG]:   File "/usr/local/lib/python3.10/http/client.py", line 1235, in _validate_host
[DEBUG]:     raise InvalidURL(f"URL can't contain control characters. {host!r} "
[DEBUG]: urllib3.exceptions.ProtocolError: ('Connection aborted.', InvalidURL('URL can\'t contain control characters. "<_io.textiowrapper name=\'examples" (found at least \' \')'))
[DEBUG]:

**Comment by spyder-griffith** [comment]
This seems to be a combination of two issues: Debug messages should not be printed unless the log level is DEBUG, and the load_data function should not treat invalid URLs as URLs; they should be treated as file names.

**Comment by spyder-griffith** [comment]
This was confirmed to be an issue with an old version.
