### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by bsmith1180** [spyderbat/spydertop#7]
After running `sudo pip install .` in the cloned repo, I get this error:

bsmith@Beast:spydertop[bugfixes]$ /usr/local/bin/spydertop
Traceback (most recent call last):
  File "/usr/local/bin/spydertop", line 5, in <module>
    from spydertop import cli
  File "/usr/local/lib/python3.8/dist-packages/spydertop/__init__.py", line 16, in <module>
    from spydertop.cli import cli
  File "/usr/local/lib/python3.8/dist-packages/spydertop/cli.py", line 20, in <module>
    from spydertop.screens import start_screen
ModuleNotFoundError: No module named 'spydertop.screens'

**Comment by spyder-griffith** [comment]
This should be fixed by #9.
